// Combine original and additional quiz scenarios
const initialQuizScenarios = [
    { scenario: "Alex notices that whenever he checks the clock, it's 11:11. He starts to believe this is a special sign or message meant just for him.", correctBias: "clustering-illusion", options: ["clustering-illusion", "confirmation-bias", "availability-heuristic", "forer-effect"], explanation: "People tend to see patterns in random events. Alex is noticing a coincidence (seeing 11:11) and attributing special meaning to it, when it's random chance." },
    { scenario: "After purchasing a new red car, Sophia suddenly notices red cars everywhere. She thinks there must be more red cars being manufactured.", correctBias: "availability-heuristic", options: ["confirmation-bias", "availability-heuristic", "clustering-illusion", "spotlight-effect"], explanation: "The Availability Heuristic causes us to notice things more after they become relevant. The number of red cars hasn't increased, but Sophia's awareness has." },
    { scenario: "After hearing about a plane crash, Marcos decides to drive, believing it's safer, despite statistics showing air travel is much safer.", correctBias: "availability-heuristic", options: ["availability-heuristic", "survivorship-bias", "pessimism-bias", "zero-risk-bias"], explanation: "The vivid, recent news of a crash makes the risk seem greater than it statistically is (Availability Heuristic)." },
    { scenario: "Despite scientific studies disproving her belief that vaccines cause autism, Jenny becomes even more convinced they are dangerous.", correctBias: "backfire-effect", options: ["confirmation-bias", "backfire-effect", "belief-bias", "reactance"], explanation: "The Backfire Effect occurs when contradictory evidence causes someone to strengthen their existing beliefs." },
    { scenario: "Tina spends hours assembling a wobbly IKEA bookshelf but tells everyone it's the best bookshelf she's ever owned.", correctBias: "ikea-effect", options: ["ikea-effect", "sunk-cost-fallacy", "self-serving-bias", "halo-effect"], explanation: "The IKEA Effect causes us to place higher value on things we've put effort into creating." },
    { scenario: "During an interview, Carlos sees the interviewer's Harvard diploma and immediately assumes they are extremely intelligent.", correctBias: "halo-effect", options: ["authority-bias", "halo-effect", "in-group-favoritism", "anchoring"], explanation: "The Halo Effect lets one positive trait (Harvard grad) influence the overall impression without evidence for other traits." },
    { scenario: "Jorge keeps investing in a failing business, saying 'I've put too much into this to give up now.'", correctBias: "sunk-cost-fallacy", options: ["optimism-bias", "status-quo-bias", "sunk-cost-fallacy", "self-serving-bias"], explanation: "The Sunk Cost Fallacy involves continuing an endeavor due to past investment, not objective current evaluation." },
    { scenario: "After losing several poker hands, Lisa thinks, 'I'm due for a win now.'", correctBias: "gamblers-fallacy", options: ["optimism-bias", "clustering-illusion", "gamblers-fallacy", "availability-cascade"], explanation: "The Gambler's Fallacy is the mistaken belief that past random events influence future independent random events." },
    { scenario: "Maria reads a vague personality description ('sometimes critical of herself...') and thinks it's remarkably accurate for her specifically.", correctBias: "forer-effect", options: ["false-consensus", "forer-effect", "blind-spot-bias", "naive-realism"], explanation: "The Forer Effect (Barnum Effect) makes people believe general statements are specifically tailored to them." },
    { scenario: "After a two-day coding workshop, David feels he's an expert programmer and applies for senior roles.", correctBias: "dunning-kruger-effect", options: ["dunning-kruger-effect", "belief-bias", "self-serving-bias", "optimism-bias"], explanation: "The Dunning-Kruger Effect leads people with limited knowledge to overestimate their expertise." }
];

const additionalQuizScenarios = [
    // Social Biases (Continuing)
    { scenario: "Mark sees a coworker arrive late to a meeting and immediately thinks, 'Typical Sarah, always so disorganized.' Later that week, Mark is late himself due to unexpected traffic and thinks, 'It wasn't my fault, the traffic was insane!'", correctBias: "fundamental-attribution-error", options: ["fundamental-attribution-error", "self-serving-bias", "confirmation-bias", "stereotyping"], explanation: "This demonstrates the Fundamental Attribution Error, where Mark attributes Sarah's lateness to her character (disorganized) but his own lateness to external circumstances (traffic)." },
    { scenario: "After successfully leading a project, Maya tells her boss it was due to her excellent leadership skills. When a later project fails, she blames unforeseen market changes and lack of team support.", correctBias: "self-serving-bias", options: ["self-serving-bias", "fundamental-attribution-error", "optimism-bias", "dunning-kruger-effect"], explanation: "The Self-Serving Bias leads individuals to attribute successes to their own abilities and failures to external factors." },
    { scenario: "During a team competition, members of the 'Blue Team' consistently rate their own team's ideas as more creative and viable than the 'Red Team's' ideas, even when objective criteria suggest otherwise.", correctBias: "in-group-favoritism", options: ["in-group-favoritism", "groupthink", "bandwagon-effect", "outgroup-homogeneity-bias"], explanation: "In-Group Favoritism is the tendency to favor members of one's own group over out-group members." },
    { scenario: "A new fashion trend starts gaining popularity online. Even though Liam initially didn't like it, he starts thinking it looks cool and considers buying clothes in that style because 'everyone seems to be doing it'.", correctBias: "bandwagon-effect", options: ["bandwagon-effect", "groupthink", "status-quo-bias", "availability-heuristic"], explanation: "The Bandwagon Effect describes the tendency for individuals to adopt certain behaviors or beliefs because many others are doing so." },
    { scenario: "A committee needs to make a quick decision. To avoid conflict and maintain harmony, members suppress their dissenting opinions and agree on a suboptimal plan, even though some have private reservations.", correctBias: "groupthink", options: ["groupthink", "false-consensus", "in-group-favoritism", "authority-bias"], explanation: "Groupthink occurs when the desire for harmony or conformity in a group results in an irrational or dysfunctional decision-making outcome." },
    { scenario: "A judge gives a harsher sentence to someone who caused an accident resulting in injury than to someone who drove just as recklessly but luckily didn't hit anyone. The judge feels the outcome reflects the driver's 'bad character'.", correctBias: "moral-luck", options: ["moral-luck", "just-world-hypothesis", "defensive-attribution", "fundamental-attribution-error"], explanation: "Moral Luck involves attributing moral standing based on the outcome of events, even if the outcome was influenced by factors beyond the person's control." },
    { scenario: "David, a strong supporter of a particular political candidate, assumes that most of his friends and colleagues also support that candidate, even without discussing it.", correctBias: "false-consensus", options: ["false-consensus", "in-group-favoritism", "confirmation-bias", "naive-realism"], explanation: "The False Consensus effect is the tendency to overestimate the degree to which other people agree with one's own opinions, values, beliefs, and behaviors." },
    { scenario: "Mia is embarrassed about a small coffee stain on her shirt and feels like everyone in the office is staring at it, when in reality, hardly anyone noticed.", correctBias: "spotlight-effect", options: ["spotlight-effect", "pessimism-bias", "availability-heuristic", "self-serving-bias"], explanation: "The Spotlight Effect is the tendency to overestimate how much other people notice our appearance or behavior." },
    { scenario: "Peter assumes everyone knows the specific jargon and complex technical details related to his specialized job when explaining a project to colleagues from a different department.", correctBias: "curse-of-knowledge", options: ["curse-of-knowledge", "dunning-kruger-effect", "authority-bias", "google-effect"], explanation: "The Curse of Knowledge is a cognitive bias where better-informed individuals find it difficult to think about problems from the perspective of lesser-informed individuals." },
    { scenario: "Seeing a young person with unconventional clothing and tattoos, an older gentleman assumes they must be irresponsible and lack a strong work ethic.", correctBias: "stereotyping", options: ["stereotyping", "halo-effect", "fundamental-attribution-error", "outgroup-homogeneity-bias"], explanation: "Stereotyping involves assuming that an individual possesses characteristics believed to be typical of their apparent group." },
    { scenario: "Fans of the losing team claim the referees were clearly biased against them, while fans of the winning team believe the officiating was fair.", correctBias: "naive-realism", options: ["naive-realism", "confirmation-bias", "in-group-favoritism", "blind-spot-bias"], explanation: "Naïve Realism is the belief that we perceive the world objectively and that others who disagree must be uninformed, irrational, or biased." },
    { scenario: "After watching a documentary about successful entrepreneurs who dropped out of college, Ben starts believing college is unnecessary for success, ignoring the vast majority who don't succeed this way.", correctBias: "survivorship-bias", options: ["survivorship-bias", "optimism-bias", "availability-heuristic", "confirmation-bias"], explanation: "Survivorship Bias is concentrating on the people or things that made it past some selection process and overlooking those that did not, typically because of their lack of visibility." },
    { scenario: "Members of a tight-knit community perceive outsiders ('those city folks') as all being the same – rushed, unfriendly, and materialistic – while seeing considerable diversity within their own group.", correctBias: "outgroup-homogeneity-bias", options: ["outgroup-homogeneity-bias", "in-group-favoritism", "stereotyping", "false-consensus"], explanation: "Outgroup Homogeneity Bias is the perception that members of an out-group are more similar to each other than members of one's own in-group are." },
    { scenario: "When asked to donate to charity, someone who recently lent a small amount of money to a friend finds themselves more willing to donate than usual.", correctBias: "ben-franklin-effect", options: ["ben-franklin-effect", "sunk-cost-fallacy", "anchoring", "reactance"], explanation: "The Ben Franklin Effect suggests that a person who has performed a favor for someone is more likely to do another favor for that person than they would be if they had *received* a favor from that person." },
    { scenario: "An emergency occurs in a crowded public place. Many people witness it, but everyone assumes someone else has already called for help or will intervene, so no one takes action immediately.", correctBias: "bystander-effect", options: ["bystander-effect", "groupthink", "moral-luck", "defensive-attribution"], explanation: "The Bystander Effect is a social psychological phenomenon where individuals are less likely to offer help to a victim when other people are present." },
    // Belief Biases (Continuing)
    { scenario: "During a heated argument about a controversial topic, Emily dismisses her opponent's well-reasoned points simply because she strongly disagrees with their final conclusion.", correctBias: "belief-bias", options: ["belief-bias", "confirmation-bias", "backfire-effect", "fundamental-attribution-error"], explanation: "Belief Bias involves evaluating the logical strength of an argument based on the plausibility of its conclusion, rather than how strongly the premises support that conclusion." },
    { scenario: "A news channel repeatedly airs dramatic footage of a rare but frightening event (like a shark attack). This leads viewers to overestimate the actual risk of such events occurring.", correctBias: "availability-cascade", options: ["availability-cascade", "availability-heuristic", "framing-effect", "pessimism-bias"], explanation: "An Availability Cascade is a self-reinforcing process where a collective belief gains more plausibility through its increasing repetition in public discourse." },
    { scenario: "An elderly person constantly remarks, 'Music today is just noise! Back in my day, music was real art.' They overlook the bad music from their youth and ignore talented modern artists.", correctBias: "declinism", options: ["declinism", "status-quo-bias", "confirmation-bias", "pessimism-bias"], explanation: "Declinism is the belief that a society or institution is tending towards decline, often involving nostalgia for the past and a negative view of the present or future." },
    { scenario: "Jordan is offered a new phone plan with better features and lower cost, but decides to stick with his current, more expensive plan because changing feels like too much hassle.", correctBias: "status-quo-bias", options: ["status-quo-bias", "sunk-cost-fallacy", "zero-risk-bias", "reactance"], explanation: "Status Quo Bias is an emotional preference for the current state of affairs, where any change from baseline is perceived as a loss." },
    { scenario: "When presented with two options for a medical procedure - one described as having a '90% survival rate' and the other as having a '10% mortality rate' - people overwhelmingly prefer the first option, despite them being statistically identical.", correctBias: "framing-effect", options: ["framing-effect", "anchoring", "availability-heuristic", "optimism-bias"], explanation: "The Framing Effect is a cognitive bias where people decide on options based on whether the options are presented with positive or negative connotations (e.g., as a loss or as a gain)." },
    { scenario: "Despite multiple credible sources debunking a conspiracy theory, Alex only seeks out websites and forums that support the theory, reinforcing his initial belief.", correctBias: "confirmation-bias", options: ["confirmation-bias", "belief-bias", "backfire-effect", "availability-heuristic"], explanation: "Confirmation Bias is the tendency to search for, interpret, favor, and recall information in a way that confirms or supports one's preexisting beliefs or hypotheses." },
    { scenario: "A politician claims that opponent's supporters are easily manipulated by sensationalist media, while asserting that their own supporters critically evaluate information and aren't swayed by propaganda.", correctBias: "third-person-effect", options: ["third-person-effect", "naive-realism", "blind-spot-bias", "in-group-favoritism"], explanation: "The Third-Person Effect predicts that people tend to perceive that mass media messages have a greater effect on others than on themselves." },
    { scenario: "A driver involved in a minor accident blames the other driver more severely because the other driver was using their phone, even though the first driver also made a mistake. The first driver thinks, 'That could never happen to me, I'm careful'.", correctBias: "defensive-attribution", options: ["defensive-attribution", "fundamental-attribution-error", "just-world-hypothesis", "self-serving-bias"], explanation: "Defensive Attribution involves blaming victims for their misfortune more when the observer feels personally similar to the victim, as a way to feel less vulnerable to the same fate." },
    { scenario: "After reading about several lottery winners in the news, Sarah starts buying lottery tickets regularly, believing her chances of winning are higher than they actually are.", correctBias: "optimism-bias", options: ["optimism-bias", "availability-heuristic", "gamblers-fallacy", "clustering-illusion"], explanation: "Optimism Bias causes a person to believe that they are less likely to experience a negative event and more likely to experience positive events compared to others." },
    { scenario: "Despite statistics showing the safety of flying, John always feels intense anxiety before a flight, convinced that something bad is likely to happen.", correctBias: "pessimism-bias", options: ["pessimism-bias", "availability-heuristic", "zero-risk-bias", "framing-effect"], explanation: "Pessimism Bias is the tendency to overestimate the likelihood of negative outcomes and underestimate positive ones." },
    { scenario: "Jessica readily points out the confirmation bias in her friend's political arguments but fails to recognize the same bias in her own reasoning on different topics.", correctBias: "blind-spot-bias", options: ["blind-spot-bias", "naive-realism", "third-person-effect", "fundamental-attribution-error"], explanation: "The Blind Spot Bias is the cognitive bias of failing to recognize one's own cognitive biases, while readily seeing the impact of bias in others." },
    { scenario: "A manager assumes their employees are primarily motivated by self-interest (like salary increases) and downplays the importance of factors like job satisfaction or recognition, even when employees state otherwise.", correctBias: "naive-cynicism", options: ["naive-cynicism", "pessimism-bias", "fundamental-attribution-error", "false-consensus"], explanation: "Naïve Cynicism is the tendency to expect others' behavior to be more egocentrically biased (motivated by self-interest) than it actually is." },
    { scenario: "A teenager is told by their parents not to hang out with a certain group of friends. Feeling their freedom is being restricted, the teenager deliberately spends more time with those friends.", correctBias: "reactance", options: ["reactance", "status-quo-bias", "backfire-effect", "bandwagon-effect"], explanation: "Reactance is a motivational reaction to offers, persons, rules, or regulations that threaten or eliminate specific behavioral freedoms. It often results in doing the opposite of what is encouraged." },
    // Memory Biases
    { scenario: "Instead of remembering his friend's phone number, Alex relies on always finding it in his phone's contacts. When his phone battery dies, he realizes he can't recall the number.", correctBias: "google-effect", options: ["google-effect", "cryptomnesia", "false-memory", "suggestibility"], explanation: "The Google Effect (or Digital Amnesia) is the tendency to forget information that can be easily found online using search engines." },
    { scenario: "During a stressful situation, like a car accident, a person perceives events as happening in slow motion.", correctBias: "tachypsychia", options: ["tachypsychia", "false-memory", "suggestibility", "pessimism-bias"], explanation: "Tachypsychia is a neurological condition that alters the perception of time, usually induced by physical exertion, drug use, or a traumatic event, often making events appear slower." },
    { scenario: "A student feels a constant nagging feeling about an unfinished assignment but easily forgets about the assignments they have already completed and submitted.", correctBias: "zeigarnik-effect", options: ["zeigarnik-effect", "google-effect", "sunk-cost-fallacy", "availability-heuristic"], explanation: "The Zeigarnik Effect states that people remember uncompleted or interrupted tasks better than completed tasks." },
    { scenario: "During a therapy session, a therapist asks leading questions like 'Did you feel abandoned when your father left?' The patient later incorporates this suggestion into their actual memories, believing they truly felt abandoned at the time.", correctBias: "suggestibility", options: ["suggestibility", "false-memory", "cryptomnesia", "confirmation-bias"], explanation: "Suggestibility is the quality of being inclined to accept and act on the suggestions of others, which can lead to the formation of false memories, especially under questioning." },
    { scenario: "Someone vividly recalls attending a childhood birthday party with specific details, but family members later confirm that party never actually happened; it was likely a story they heard or a dream.", correctBias: "false-memory", options: ["false-memory", "suggestibility", "cryptomnesia", "google-effect"], explanation: "A False Memory is a psychological phenomenon where a person recalls something that did not happen or recalls it differently from the way it actually happened." },
    { scenario: "A songwriter believes they have created a completely original melody, but it later turns out they subconsciously recalled a tune they heard years ago, mistaking the memory for original inspiration.", correctBias: "cryptomnesia", options: ["cryptomnesia", "false-memory", "suggestibility", "google-effect"], explanation: "Cryptomnesia occurs when a forgotten memory returns without it being recognized as such by the subject, who believes it is something new and original." },
    // Learning Biases (Continuing)
    { scenario: "A programmer relies heavily on an automated code-checking tool. They approve a suggestion from the tool that introduces a subtle bug, assuming the automated system must be correct.", correctBias: "automation-bias", options: ["automation-bias", "anchoring", "curse-of-knowledge", "google-effect"], explanation: "Automation Bias is the tendency to excessively depend on automated systems, potentially trusting them even when they provide incorrect information." },
    { scenario: "A patient given a sugar pill (placebo) for pain relief reports feeling significantly better, believing they received actual medication.", correctBias: "placebo-effect", options: ["placebo-effect", "optimism-bias", "suggestibility", "self-serving-bias"], explanation: "The Placebo Effect occurs when a simulated or otherwise ineffective treatment for a medical condition leads to perceived or actual improvement simply because the recipient expects or believes it will work." },
     // Money Biases (Continuing)
    { scenario: "When choosing insurance, a customer opts for a plan that completely eliminates the risk of a very specific, minor issue, rather than a plan that significantly reduces the risk of several more common, larger issues.", correctBias: "zero-risk-bias", options: ["zero-risk-bias", "pessimism-bias", "status-quo-bias", "anchoring"], explanation: "Zero-Risk Bias is the tendency to prefer options that completely eliminate a risk, even if alternative options provide a greater overall risk reduction." },
    { scenario: "Liam spent a lot of time and effort building a custom piece of furniture. Even though it has flaws, he values it far more highly than a similar, professionally made piece he could buy for less.", correctBias: "ikea-effect", options: ["ikea-effect", "sunk-cost-fallacy", "status-quo-bias", "self-serving-bias"], explanation: "The IKEA Effect causes people to place a disproportionately high value on products they partially created." },
     // Politics Biases
    { scenario: "A city council spends two hours debating the color to paint the new community bike sheds, but only allocates 15 minutes to discussing a complex multi-million dollar infrastructure project.", correctBias: "law-of-triviality", options: ["law-of-triviality", "anchoring", "groupthink", "framing-effect"], explanation: "The Law of Triviality (also known as Parkinson's Law of Triviality or 'bike-shedding') argues that organizations give disproportionate weight to trivial issues." },
    { scenario: "During a political rally, supporters unquestioningly accept the statements made by their preferred candidate, viewing them as inherently trustworthy and knowledgeable simply due to their position.", correctBias: "authority-bias", options: ["authority-bias", "halo-effect", "in-group-favoritism", "confirmation-bias"], explanation: "Authority Bias is the tendency to attribute greater accuracy and value to the opinion of an authority figure, irrespective of the content." }
];

// Combine the arrays
const quizScenarios = initialQuizScenarios.concat(additionalQuizScenarios);
